/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TicketsIndexRouteImport } from './routes/tickets/index'
import { Route as SyndicatesIndexRouteImport } from './routes/syndicates/index'
import { Route as ResultsIndexRouteImport } from './routes/results/index'
import { Route as PlayIndexRouteImport } from './routes/play/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as SyndicatesSyndicateIdRouteImport } from './routes/syndicates/$syndicateId'
import { Route as PlayQuickPickRouteImport } from './routes/play/quick-pick'
import { Route as LearnWhitepaperRouteImport } from './routes/learn/whitepaper'
import { Route as LearnRolldownRouteImport } from './routes/learn/rolldown'
import { Route as ApiTrpcSplatRouteImport } from './routes/api/trpc/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsIndexRoute = TicketsIndexRouteImport.update({
  id: '/tickets/',
  path: '/tickets/',
  getParentRoute: () => rootRouteImport,
} as any)
const SyndicatesIndexRoute = SyndicatesIndexRouteImport.update({
  id: '/syndicates/',
  path: '/syndicates/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsIndexRoute = ResultsIndexRouteImport.update({
  id: '/results/',
  path: '/results/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayIndexRoute = PlayIndexRouteImport.update({
  id: '/play/',
  path: '/play/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const SyndicatesSyndicateIdRoute = SyndicatesSyndicateIdRouteImport.update({
  id: '/syndicates/$syndicateId',
  path: '/syndicates/$syndicateId',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayQuickPickRoute = PlayQuickPickRouteImport.update({
  id: '/play/quick-pick',
  path: '/play/quick-pick',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnWhitepaperRoute = LearnWhitepaperRouteImport.update({
  id: '/learn/whitepaper',
  path: '/learn/whitepaper',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRolldownRoute = LearnRolldownRouteImport.update({
  id: '/learn/rolldown',
  path: '/learn/rolldown',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/learn/rolldown': typeof LearnRolldownRoute
  '/learn/whitepaper': typeof LearnWhitepaperRoute
  '/play/quick-pick': typeof PlayQuickPickRoute
  '/syndicates/$syndicateId': typeof SyndicatesSyndicateIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/play/': typeof PlayIndexRoute
  '/results/': typeof ResultsIndexRoute
  '/syndicates/': typeof SyndicatesIndexRoute
  '/tickets/': typeof TicketsIndexRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/learn/rolldown': typeof LearnRolldownRoute
  '/learn/whitepaper': typeof LearnWhitepaperRoute
  '/play/quick-pick': typeof PlayQuickPickRoute
  '/syndicates/$syndicateId': typeof SyndicatesSyndicateIdRoute
  '/dashboard': typeof DashboardIndexRoute
  '/play': typeof PlayIndexRoute
  '/results': typeof ResultsIndexRoute
  '/syndicates': typeof SyndicatesIndexRoute
  '/tickets': typeof TicketsIndexRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/learn/rolldown': typeof LearnRolldownRoute
  '/learn/whitepaper': typeof LearnWhitepaperRoute
  '/play/quick-pick': typeof PlayQuickPickRoute
  '/syndicates/$syndicateId': typeof SyndicatesSyndicateIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/play/': typeof PlayIndexRoute
  '/results/': typeof ResultsIndexRoute
  '/syndicates/': typeof SyndicatesIndexRoute
  '/tickets/': typeof TicketsIndexRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/learn/rolldown'
    | '/learn/whitepaper'
    | '/play/quick-pick'
    | '/syndicates/$syndicateId'
    | '/dashboard/'
    | '/play/'
    | '/results/'
    | '/syndicates/'
    | '/tickets/'
    | '/api/trpc/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/learn/rolldown'
    | '/learn/whitepaper'
    | '/play/quick-pick'
    | '/syndicates/$syndicateId'
    | '/dashboard'
    | '/play'
    | '/results'
    | '/syndicates'
    | '/tickets'
    | '/api/trpc/$'
  id:
    | '__root__'
    | '/'
    | '/learn/rolldown'
    | '/learn/whitepaper'
    | '/play/quick-pick'
    | '/syndicates/$syndicateId'
    | '/dashboard/'
    | '/play/'
    | '/results/'
    | '/syndicates/'
    | '/tickets/'
    | '/api/trpc/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LearnRolldownRoute: typeof LearnRolldownRoute
  LearnWhitepaperRoute: typeof LearnWhitepaperRoute
  PlayQuickPickRoute: typeof PlayQuickPickRoute
  SyndicatesSyndicateIdRoute: typeof SyndicatesSyndicateIdRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  PlayIndexRoute: typeof PlayIndexRoute
  ResultsIndexRoute: typeof ResultsIndexRoute
  SyndicatesIndexRoute: typeof SyndicatesIndexRoute
  TicketsIndexRoute: typeof TicketsIndexRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets/': {
      id: '/tickets/'
      path: '/tickets'
      fullPath: '/tickets/'
      preLoaderRoute: typeof TicketsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/syndicates/': {
      id: '/syndicates/'
      path: '/syndicates'
      fullPath: '/syndicates/'
      preLoaderRoute: typeof SyndicatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results/': {
      id: '/results/'
      path: '/results'
      fullPath: '/results/'
      preLoaderRoute: typeof ResultsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/': {
      id: '/play/'
      path: '/play'
      fullPath: '/play/'
      preLoaderRoute: typeof PlayIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/syndicates/$syndicateId': {
      id: '/syndicates/$syndicateId'
      path: '/syndicates/$syndicateId'
      fullPath: '/syndicates/$syndicateId'
      preLoaderRoute: typeof SyndicatesSyndicateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/quick-pick': {
      id: '/play/quick-pick'
      path: '/play/quick-pick'
      fullPath: '/play/quick-pick'
      preLoaderRoute: typeof PlayQuickPickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/whitepaper': {
      id: '/learn/whitepaper'
      path: '/learn/whitepaper'
      fullPath: '/learn/whitepaper'
      preLoaderRoute: typeof LearnWhitepaperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/rolldown': {
      id: '/learn/rolldown'
      path: '/learn/rolldown'
      fullPath: '/learn/rolldown'
      preLoaderRoute: typeof LearnRolldownRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LearnRolldownRoute: LearnRolldownRoute,
  LearnWhitepaperRoute: LearnWhitepaperRoute,
  PlayQuickPickRoute: PlayQuickPickRoute,
  SyndicatesSyndicateIdRoute: SyndicatesSyndicateIdRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  PlayIndexRoute: PlayIndexRoute,
  ResultsIndexRoute: ResultsIndexRoute,
  SyndicatesIndexRoute: SyndicatesIndexRoute,
  TicketsIndexRoute: TicketsIndexRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
